/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppReflection.h"

#include "..\..\Source\Reflection\DescriptableInterfaces.cpp"
#include "..\..\Source\Reflection\DescriptableInterfaces_Log.cpp"
#include "..\..\Source\Reflection\DescriptableInterfaces_Metaonly.cpp"
#include "..\..\Source\Reflection\DescriptableObject.cpp"
#include "..\..\Source\Reflection\DescriptableValue.cpp"
#include "..\..\Source\Reflection\Metadata\Metadata.cpp"
#include "..\..\Source\Reflection\Predefined\PredefinedTypes.cpp"
#include "..\..\Source\Reflection\Reflection\Reflection.cpp"
